turbot/steampipe-plugin-azuread

README.md
azuread/connection_config.go
azuread/service.go
config/azuread.spc
docs/index.md
docs/notes.md
docs/tables/azuread_group.md
docs/tables/azuread_user.md

<details>
```
```
</details>
<details>
```
```
</details>

Add docs for plugin steampipe hub home page and tables `azuread_group` and `azuread_user`

---

azuread/plugin.go
azuread/table_azuread_application.go
azuread/table_azuread_directory_role.go
azuread/table_azuread_domain.go
azuread/table_azuread_group.go
azuread/table_azuread_identity_provider.go
azuread/table_azuread_service_principal.go
azuread/table_azuread_user.go
azuread/utils.go
docs/tables/azuread_application.md
docs/tables/azuread_directory_role.md
docs/tables/azuread_domain.md
docs/tables/azuread_group.md
docs/tables/azuread_identity_provider.md
docs/tables/azuread_service_principal.md
docs/tables/azuread_user.md

<details>
```
```
</details>
<details>
```
```
</details>

Add tables azuread_application, azuread_domain, azuread_service_principal, azuread_directory_role, azuread_identity_provider closes #7

---

docs/tables/azuread_user.md

<details>
```
```
</details>
<details>
```
```
</details>

azuread_user > directory_role returns null in plugin. closes #18

---

azuread/plugin.go
azuread/table_azuread_conditional_access_policy.go
docs/tables/azuread_conditional_access_policy.md

<details>
```
```
</details>
<details>
```sql
select
id,
display_name,
state,
created_date_time,
built_in_controls
from
azuread_conditional_access_policy;
```
```
+--------------------------------------+--------------+-----------------------------------+---------------------+-------------------+
| id                                   | display_name | state                             | created_date_time   | built_in_controls |
+--------------------------------------+--------------+-----------------------------------+---------------------+-------------------+
| 7965ea90-2ad8-41f1-90d5-aa6ca81af555 | test-mfa     | enabledForReportingButNotEnforced | 2021-09-03 11:10:33 | ["mfa"]           | …
```

Add table azuread_conditional_access_policy closes #19

---

azuread/table_azuread_group.go

<details>
```
```
</details>
<details>
```sql
select 
display_name, 
id, 
on_premises_net_bios_name
from 
azuread_group;
```
```
+--------------+--------------------------------------+---------------------------+
| display_name | id                                   | on_premises_net_bios_name |
+--------------+--------------------------------------+---------------------------+
| test-mfa-grp | 518d0e06-c613-4d8e-b716-1ef3cb7c96de | <null>                    |
| All Company  | 75c93af9-7186-44e0-9444-b58d335575d3 | <null>                    |
+--------------+--------------------------------------+---------------------------+
```
</details>

"Error: interfaceToColumnValue failed for column 'on_premises_net_bios_name': found X, expected number". Fixes #24

---

docs/tables/azuread_service_principal.md

<details>
```
> select
display_name,
id,
app_display_name
from
azuread_service_principal;
+----------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------+
| display_name                                                                     | id                                   | app_display_name                                                                 |
+----------------------------------------------------------------------------------+--------------------------------------+----------------------------------------------------------------------------------+
| Microsoft Teams Bots …
```

Fix example queries in azuread_service_principal table. Fixes #28

---

azuread/table_azuread_user.go

<details>
```
```
</details>
<details>
```
steampipe query "select on_premises_immutable_id from azuread_user"
+--------------------------+
| on_premises_immutable_id |
+--------------------------+
| <null>                   |
| AADBackdoor              |
+--------------------------+
```
</details>

Add on_premises_immutable_id column to azuread_user table

---

azuread/connection_config.go
azuread/plugin.go
azuread/service.go
azuread/table_azuread_application.go
azuread/table_azuread_conditional_access_policy.go
azuread/table_azuread_directory_role.go
azuread/table_azuread_domain.go
azuread/table_azuread_group.go
azuread/table_azuread_identity_provider.go
azuread/table_azuread_service_principal.go
azuread/table_azuread_sign_in_report.go
azuread/table_azuread_user.go
azuread/utils.go
go.mod
go.sum
main.go

<details>
```
select
display_name,
id
from
azuread_application
where
not is_authorization_service_enabled;
+----------------------------------------------------------------------------------+--------------------------------------+
| display_name                                                                     | id                                   |
+----------------------------------------------------------------------------------+--------------------------------------+
| rup-testSP-20190822194017                                                        | 1c572fca-03e2-4c9c-a78d-9d0d5a3xxx |
| testtagsSP-20200224115309                                                        | 233977fe-9f72-4b08-92a2-c73dbxxxxxx |
| Turbot Dev No Access …
```

Recompile plugin with steampipe-plugin-sdk v2.1.1

---

azuread/table_azuread_application.go
azuread/table_azuread_conditional_access_policy.go
azuread/table_azuread_directory_role.go
azuread/table_azuread_domain.go
azuread/table_azuread_group.go
azuread/table_azuread_identity_provider.go
azuread/table_azuread_service_principal.go
azuread/table_azuread_sign_in_report.go
azuread/table_azuread_user.go
azuread/utils.go

<details>
```
> select * from azuread_application where display_name = 'test-clusterSP-20190822160005' and app_id = '3c723985-7153-46e1-be37-c184dca79a9b';
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| display_name                  | id                                   | app_id                               | created_date_time         | is_authorization_service_enabled | oauth2_require_post_respons
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| …
```

Update tables for better use of API filters, context cancellation in list calls and page limiting for limit clause in query closes #42

---

.github/workflows/golangci-lint.yml
.github/workflows/stale.yml

Add stale workflow and update golangci-lint workflow

---

CHANGELOG.md

Add CHANGELOG for v0.5.1

---

azuread/plugin.go
azuread/table_azuread_authorization_policy.go
azuread/transforms.go
docs/tables/azuread_authorization_policy.md

Add table azuread_authorization_policy. Closes #66

---

.github/workflows/golangci-lint.yml
.github/workflows/registry-publish.yml

Update workflows to use the 1.19 Go version

---

azuread/table_azuread_directory_audit_report.go

Update table `azuread_directory_audit_report` to use `steampipe-plugin-sdk` v4.1.7

---

azuread/table_azuread_admin_consent_request_policy.go

Update value of column `title` in table `azuread_admin_consent_request_policy`

---

CHANGELOG.md

Add CHANGELOG for v0.8.2

---

azuread/table_azuread_sign_in_report.go

Update table `azuread_sign_in_report` to modify `ip_address` column type as `ColumnType_STRING` instead of `ColumnType_IPADDR`. Closes #94

---

docs/tables/azuread_device.md
docs/tables/azuread_directory_setting.md

Update example query for tables `azuread_device` and `azuread_directory_setting`

---

azuread/table_azuread_user.go

<details>
```
select title, department from azuread_user where department is not null
+------------+------------+
| title      | department |
+------------+------------+
| Ved Mishra | test       |
+------------+------------+
```
</details>

Add department column to azuread_user table closes #131

---

azuread/service.go

Add chinacloud endpoint and scope based on the env

---

azuread/transforms.go
docs/tables/azuread_authorization_policy.md

Added allowedToCreateTenants field under default_user_role_permissions column of azuread_authorization_policy table (#243)

---

azuread/plugin.go
azuread/table_azuread_cross_tenant_access_policy.go
azuread/transforms.go
docs/tables/azuread_cross_tenant_access_policy.md

<details>
```
> select * from azuread_cross_tenant_access_policy
+--------------------------------------+-------------------------+------------------------------------------------------------------+----------------------->
| tenant_id                            | id                      | display_name                                                     | allowed_cloud_endpoint>
+--------------------------------------+-------------------------+------------------------------------------------------------------+----------------------->
| ********-7da0-4cea-abeb-************ | crossTenantAccessPolicy | CrossTenantAccessPolicy for ********-7da0-4cea-abeb-************ | []                    >
+--------------------------------------+-------------------------+---------- …
```

Add table azuread_cross_tenant_access_policy
